name: Publish unzipall to PyPI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Trigger only on version tags like v0.1.0

permissions:
  contents: read

jobs:
  build-and-publish:
    name: Build and Upload to PyPI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install build twine
    - name: Build unzipall
      run: python -m build

    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*
